name: realty-data-collect
version: "0.0.1"
description: Realty data collection
maintainer: Alex Babkin
stability: experimental
license: MIT

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
    
extra-source-files:
  - README.md
  - stack.yaml

dependencies:
  - aeson
  - attoparsec
  - base
  - base64-bytestring
  - cassava
  - data-default
  - extra
  - hashable
  - http-client
  - http-client-tls
  - lens
  - qmuli
  - protolude
  - scientific
  - servant
  - servant-client
  - text
  - unordered-containers
  - vector

library:
  source-dirs: lib

executables:
  realty-data-collect:
    main: Main.hs
    source-dirs: app
    dependencies:
      - realty-data-collect
    

