resolver: lts-11.7

packages:
- '.'
- location:
    git: https://github.com/ababkin/qmuli.git
    commit: 3f9a2a47b512809c46987120d497131fde19eb78
  extra-dep: true
- location:
    git: https://github.com/frontrowed/stratosphere.git
    commit: 6b9b0748c9a57ce2ea0e642211ee6a13c3cd97f3
  extra-dep: true
- location:
    git: https://github.com/abailly/system-extra.git
    commit: 4091624e191c8e2bcd4bbdffebee53e655377bdb
  extra-dep: true
- location:
    git: https://github.com/brendanhay/amazonka.git
    commit: 9aa47c267631339a32a1a4ea373b1319145662e2
    subdirs:
    - amazonka
    - amazonka-cloudformation
    - amazonka-cloudwatch-logs
    - amazonka-cognito-identity
    - amazonka-cognito-idp
    - amazonka-dynamodb
    - amazonka-iam
    - amazonka-lambda
    - amazonka-s3
    - core
  extra-dep: true

    
extra-deps:
  - aeson-1.3.0.0


flags: {}

extra-package-dbs: []

ghc-options:
  "qmuli-example-app": 
    # -funfolding-use-threshold=16 -O2 -optc-O3
    -O
    -Wall
    -Wno-unused-imports 
    -Wno-unused-matches 
    -Wno-unused-do-bind
    -Werror

