resolver: nightly-2018-06-02

packages:
- '.'
- '../qmuli'
  #- location:
  #  git: https://github.com/ababkin/qmuli.git
  #  commit: dff06a65ca0e9e058463d8a9054a0ffb2519e4a7
  #extra-dep: true
- location:
    git: https://github.com/ababkin/system-extra.git
    commit: 0ec5b3ca62bd73a4df6f29b99b654071a0262f18
  extra-dep: true
- location:
    git: https://github.com/brendanhay/amazonka.git
    commit: 248f7b2a7248222cc21cef6194cd1872ba99ac5d
    subdirs:
    - amazonka
  extra-dep: true

extra-deps: []


flags: {}

extra-package-dbs: []

ghc-options:
  "realty-data-collect": 
    # -funfolding-use-threshold=16 -O2 -optc-O3
    -O0
    -Wall
    -Wno-unused-imports 
    -Wno-unused-matches 
    -Wno-unused-do-bind
    -Werror


