name: log-test
version: "0.0.1"
maintainer: Alex Babkin
stability: experimental
license: MIT

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
    
dependencies:
  - aeson
  - base
  - data-default
  - lens
  - protolude
  - qmuli


library:
  source-dirs: lib

executables:
  log-test:
    main: Main.hs
    source-dirs: app
    dependencies:
      - log-test
    

